using System.Collections.Immutable;
using System.Text.Json.Serialization;
using Freenaute.Freebox.Mapper.Contracts.SystemHome;
using Freenaute.Freebox.Mapper.Contracts.Primitives;

namespace Freenaute.Freebox.Mapper.Serialization;

/// <summary>Generated metadata for the reviewed System, Home and Profile wire contracts.</summary>
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Default,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(DefaultModeMigrationStatus))]
[JsonSerializable(typeof(HomeAdapter))]
[JsonSerializable(typeof(HomeAdapterStatus))]
[JsonSerializable(typeof(HomeAdapterStatusRequest))]
[JsonSerializable(typeof(HomeAdapterType))]
[JsonSerializable(typeof(HomeEndpointAccess))]
[JsonSerializable(typeof(HomeEndpointDisplay))]
[JsonSerializable(typeof(HomeEndpointKind))]
[JsonSerializable(typeof(HomeEndpointValueRequest))]
[JsonSerializable(typeof(HomeEndpointValueType))]
[JsonSerializable(typeof(HomeEndpointVisibility))]
[JsonSerializable(typeof(HomeIoValue))]
[JsonSerializable(typeof(HomeNode))]
[JsonSerializable(typeof(HomeNodeEndpoint))]
[JsonSerializable(typeof(HomeNodeEndpointUi))]
[JsonSerializable(typeof(HomeNodeEndpointValue))]
[JsonSerializable(typeof(HomeNodeGroup))]
[JsonSerializable(typeof(HomeNodeStatus))]
[JsonSerializable(typeof(HomeNodeType))]
[JsonSerializable(typeof(HomePairingNextRequest))]
[JsonSerializable(typeof(HomePairingStartRequest))]
[JsonSerializable(typeof(HomePairingStep))]
[JsonSerializable(typeof(HomePairingStepField))]
[JsonSerializable(typeof(HomePairingStopRequest))]
[JsonSerializable(typeof(HomePairingWidget))]
[JsonSerializable(typeof(HomeTile))]
[JsonSerializable(typeof(HomeTileAction))]
[JsonSerializable(typeof(HomeTileData))]
[JsonSerializable(typeof(HomeTileType))]
[JsonSerializable(typeof(HomeTileValueType))]
[JsonSerializable(typeof(LanguageSupport))]
[JsonSerializable(typeof(LcdConfig))]
[JsonSerializable(typeof(LcdConfigPatch))]
[JsonSerializable(typeof(LcdLedAnimation))]
[JsonSerializable(typeof(LcdScreensaver))]
[JsonSerializable(typeof(LedstripPlanning))]
[JsonSerializable(typeof(LedstripPlanningMode))]
[JsonSerializable(typeof(LedstripPlanningUpdate))]
[JsonSerializable(typeof(LedstripStatus))]
[JsonSerializable(typeof(NetworkControl))]
[JsonSerializable(typeof(NetworkControlHosts))]
[JsonSerializable(typeof(NetworkControlMode))]
[JsonSerializable(typeof(NetworkControlRule))]
[JsonSerializable(typeof(NetworkControlUpdate))]
[JsonSerializable(typeof(Profile))]
[JsonSerializable(typeof(ProfileCreateRequest))]
[JsonSerializable(typeof(ProfileCreated))]
[JsonSerializable(typeof(RenameHomeNodeRequest))]
[JsonSerializable(typeof(SetLanguageRequest))]
[JsonSerializable(typeof(StandbyConfig))]
[JsonSerializable(typeof(StandbyConfigUpdate))]
[JsonSerializable(typeof(StandbyPlanningMode))]
[JsonSerializable(typeof(StandbyStatus))]
[JsonSerializable(typeof(SystemConfig))]
[JsonSerializable(typeof(SystemConfigExpansion))]
[JsonSerializable(typeof(SystemConfigFan))]
[JsonSerializable(typeof(SystemConfigSensor))]
[JsonSerializable(typeof(SystemDiskStatus))]
[JsonSerializable(typeof(SystemExpansionType))]
[JsonSerializable(typeof(SystemModelInfo))]
[JsonSerializable(typeof(SystemUpdateState))]
[JsonSerializable(typeof(SystemUpgradeState))]
[JsonSerializable(typeof(UpdateStatus))]
[JsonSerializable(typeof(UpgradeState))]
[JsonSerializable(typeof(ImmutableArray<HomeAdapter>), TypeInfoPropertyName = "HomeAdapters")]
[JsonSerializable(typeof(ImmutableArray<HomeNode>), TypeInfoPropertyName = "HomeNodes")]
[JsonSerializable(typeof(ImmutableArray<HomeTile>), TypeInfoPropertyName = "HomeTiles")]
[JsonSerializable(typeof(ImmutableArray<Profile>), TypeInfoPropertyName = "Profiles")]
[JsonSerializable(typeof(ImmutableArray<NetworkControlRule>), TypeInfoPropertyName = "NetworkControlRules")]
[JsonSerializable(typeof(ImmutableArray<bool>), TypeInfoPropertyName = "BooleanArray")]
[JsonSerializable(typeof(ImmutableArray<string>), TypeInfoPropertyName = "StringArray")]
[JsonSerializable(typeof(StringOrInteger))]
public sealed partial class SystemHomeJsonSerializerContext : JsonSerializerContext;
